name: o_sync
description: >
  A Mass Data Transaction package for Flutter/Dart. 
  Provides offline-first sync with Hive, network requests, and file handling.
version: 0.0.4+1
homepage: https://github.com/altalha201/o_sync
repository: https://github.com/altalha201/o_sync
issue_tracker: https://github.com/altalha201/o_sync/issues
topics:
  - hive
  - sync
  - offline
  - http
  - data-management

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  http: ^1.3.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_ce_generator: ^1.8.2
  # run code generation:
  # dart run build_runner build --delete-conflicting-outputs

flutter:
# Example for future assets (currently empty)
# assets:
#   - images/
