// Copyright (c) 2025 OSync Authors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the root directory.

// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:o_sync/src/functionality/object/models/basic_info/basic_info.dart';
import 'package:o_sync/src/functionality/object/models/down/download_table.dart';
import 'package:o_sync/src/functionality/object/models/file/file_table.dart';
import 'package:o_sync/src/functionality/object/models/up/upload_table.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(OSBasicInfoAdapter());
    registerAdapter(OSDownloadDataAdapter());
    registerAdapter(OSDownloadTableAdapter());
    registerAdapter(OSFileTableAdapter());
    registerAdapter(OSUploadDataAdapter());
    registerAdapter(OSUploadTableAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(OSBasicInfoAdapter());
    registerAdapter(OSDownloadDataAdapter());
    registerAdapter(OSDownloadTableAdapter());
    registerAdapter(OSFileTableAdapter());
    registerAdapter(OSUploadDataAdapter());
    registerAdapter(OSUploadTableAdapter());
  }
}
